# Pokemon(ID,NAME)

In [1]:
import requests
import bs4 as bs

In [2]:
req=requests.get("https://pokemondb.net/pokedex/national?fbclid=IwAR3XHXrBQQ9RjiAinVxDETVQkn9CdtRSMnx6Qgk4Sn96zOhuA3450e37rUk")

In [3]:
soup=bs.BeautifulSoup(req.text,'html.parser')

In [4]:
data=soup.find_all('div',{'class':'infocard'})

In [5]:
import pandas as pd
df=pd.DataFrame(columns={'ID','Nom'})
for item in data:  
  Nom=item.find_all('a',{'class':'ent-name'})[0].text.encode("utf_8")
  id=item.find_all('small')[0].text.encode("utf_8")
  
  df=df.append({'ID':id.decode("utf-8"),'Nom':Nom.decode("utf-8")},ignore_index=True)
print(df)

       ID          Nom
0    #001    Bulbasaur
1    #002      Ivysaur
2    #003     Venusaur
3    #004   Charmander
4    #005   Charmeleon
5    #006    Charizard
6    #007     Squirtle
7    #008    Wartortle
8    #009    Blastoise
9    #010     Caterpie
10   #011      Metapod
11   #012   Butterfree
12   #013       Weedle
13   #014       Kakuna
14   #015     Beedrill
15   #016       Pidgey
16   #017    Pidgeotto
17   #018      Pidgeot
18   #019      Rattata
19   #020     Raticate
20   #021      Spearow
21   #022       Fearow
22   #023        Ekans
23   #024        Arbok
24   #025      Pikachu
25   #026       Raichu
26   #027    Sandshrew
27   #028    Sandslash
28   #029     Nidoran♀
29   #030     Nidorina
..    ...          ...
779  #780       Drampa
780  #781     Dhelmise
781  #782     Jangmo-o
782  #783     Hakamo-o
783  #784      Kommo-o
784  #785    Tapu Koko
785  #786    Tapu Lele
786  #787    Tapu Bulu
787  #788    Tapu Fini
788  #789       Cosmog
789  #790      Cosmoem
790  #791     Solgaleo
791  #792       Lunala
792  #793     Nihilego
793  #794     Buzzwole
794  #795    Pheromosa
795  #796    Xurkitree
796  #797   Celesteela
797  #798      Kartana
798  #799     Guzzlord
799  #800     Necrozma
800  #801     Magearna
801  #802    Marshadow
802  #803      Poipole
803  #804    Naganadel
804  #805    Stakataka
805  #806  Blacephalon
806  #807      Zeraora
807  #808       Meltan
808  #809     Melmetal

[809 rows x 2 columns]

In [6]:
df

       ID          Nom
0    #001    Bulbasaur
1    #002      Ivysaur
2    #003     Venusaur
3    #004   Charmander
4    #005   Charmeleon
5    #006    Charizard
6    #007     Squirtle
7    #008    Wartortle
8    #009    Blastoise
9    #010     Caterpie
10   #011      Metapod
11   #012   Butterfree
12   #013       Weedle
13   #014       Kakuna
14   #015     Beedrill
15   #016       Pidgey
16   #017    Pidgeotto
17   #018      Pidgeot
18   #019      Rattata
19   #020     Raticate
20   #021      Spearow
21   #022       Fearow
22   #023        Ekans
23   #024        Arbok
24   #025      Pikachu
25   #026       Raichu
26   #027    Sandshrew
27   #028    Sandslash
28   #029     Nidoran♀
29   #030     Nidorina
..    ...          ...
779  #780       Drampa
780  #781     Dhelmise
781  #782     Jangmo-o
782  #783     Hakamo-o
783  #784      Kommo-o
784  #785    Tapu Koko
785  #786    Tapu Lele
786  #787    Tapu Bulu
787  #788    Tapu Fini
788  #789       Cosmog
789  #790      Cosmoem
790  #791     Solgaleo
791  #792       Lunala
792  #793     Nihilego
793  #794     Buzzwole
794  #795    Pheromosa
795  #796    Xurkitree
796  #797   Celesteela
797  #798      Kartana
798  #799     Guzzlord
799  #800     Necrozma
800  #801     Magearna
801  #802    Marshadow
802  #803      Poipole
803  #804    Naganadel
804  #805    Stakataka
805  #806  Blacephalon
806  #807      Zeraora
807  #808       Meltan
808  #809     Melmetal

[809 rows x 2 columns]

In [9]:
df.to_csv('C:\\Users\\dell\\Desktop\\Pokemon_Scraping\\Pokemon_ID_Names.csv')